// Generated by ReScript, PLEASE EDIT WITH CARE

import * as State from "../state.bs.js";
import * as React from "react";
import * as Utils from "jotai/utils";

function SumComp(Props) {
  var sum = Utils.useAtomValue(State.sum);
  return React.createElement("h1", undefined, "sum: " + String(sum));
}

var Int;

var make = SumComp;

export {
  Int ,
  make ,
  
}
/* State Not a pure module */
