// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

var a = 1;

var b = 2;

function flatMap2(a, b, fn) {
  if (a !== undefined && b !== undefined) {
    return Curry._2(fn, Caml_option.valFromOption(a), Caml_option.valFromOption(b));
  }
  
}

var res = flatMap2(a, b, (function (a, b) {
        return a + b | 0;
      }));

var $$Option;

export {
  $$Option ,
  a ,
  b ,
  flatMap2 ,
  res ,
  
}
/* res Not a pure module */
