// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";

function make(floor) {
  return floor;
}

function toString(prim) {
  return String(prim);
}

function getShift(floorA, floorB) {
  if (Caml_obj.caml_greaterthan(floorA, floorB)) {
    return /* Down */1;
  } else if (Caml_obj.caml_lessthan(floorA, floorB)) {
    return /* Up */0;
  } else {
    return /* Still */2;
  }
}

function moveToward(current, target) {
  var shift = getShift(current, target);
  switch (shift) {
    case /* Up */0 :
        return current + 1 | 0;
    case /* Down */1 :
        return current - 1 | 0;
    case /* Still */2 :
        return current;
    
  }
}

var empty = 0;

export {
  empty ,
  make ,
  toString ,
  moveToward ,
  
}
/* No side effect */
