// Generated by ReScript, PLEASE EDIT WITH CARE


function toString(prim) {
  return String(prim);
}

function ofInt(floor) {
  return floor;
}

function shiftBy(floor, shift) {
  return floor + shift | 0;
}

var empty = 0;

export {
  empty ,
  toString ,
  ofInt ,
  shiftBy ,
  
}
/* No side effect */
