// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dice from "./dice.bs.js";
import * as Hand from "./hand.bs.js";
import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as StepsLeft from "./stepsLeft.bs.js";

var empty = {
  TAG: /* Play */0,
  _0: Hand.empty,
  _1: StepsLeft.empty
};

function reducer(game, action) {
  if (game.TAG !== /* Play */0) {
    if (action === 0) {
      return empty;
    } else {
      return game;
    }
  }
  var steps = game._1;
  var hand = game._0;
  if (typeof action === "number") {
    if (action !== 0) {
      if (StepsLeft.next(steps) === /* Done */0) {
        return {
                TAG: /* Result */1,
                _0: Hand.isEnough(hand) ? /* Win */0 : /* Loose */1
              };
      } else {
        return {
                TAG: /* Play */0,
                _0: Hand.shuffle(hand),
                _1: StepsLeft.next(steps)
              };
      }
    } else if (action === 0) {
      return empty;
    } else {
      return game;
    }
  }
  var index = action._0;
  if (Belt_List.length(Belt_List.keep(Hand.toggleAt(hand, index), Dice.isInGame)) === 5) {
    return {
            TAG: /* Result */1,
            _0: Hand.isEnough(hand) ? /* Win */0 : /* Loose */1
          };
  } else {
    return {
            TAG: /* Play */0,
            _0: Hand.toggleAt(hand, index),
            _1: steps
          };
  }
}

function getSum(game) {
  if (game.TAG === /* Play */0) {
    return Hand.getSum(game._0);
  } else {
    return 0;
  }
}

var List;

export {
  List ,
  empty ,
  reducer ,
  getSum ,
  
}
/* Hand Not a pure module */
