// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dice from "./dice.bs.js";
import * as Belt_List from "rescript/lib/es6/belt_List.js";

var empty = Belt_List.map(Belt_List.make(5, Dice.empty), Dice.shuffle);

function shuffle(hand) {
  return Belt_List.map(hand, Dice.shuffle);
}

function toggleAt(hand, index) {
  return Belt_List.mapWithIndex(hand, (function (i, dice) {
                if (i === index) {
                  return Dice.toggle(dice);
                } else {
                  return dice;
                }
              }));
}

function getSum(hand) {
  return Belt_List.reduce(Belt_List.map(hand, Dice.toNum), 0, (function (sum, diceSum) {
                return sum + diceSum | 0;
              }));
}

function isEnough(hand) {
  return getSum(hand) > 25;
}

var List;

var handLength = 5;

export {
  List ,
  handLength ,
  empty ,
  shuffle ,
  toggleAt ,
  getSum ,
  isEnough ,
  
}
/* empty Not a pure module */
