// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Floor from "./floor.bs.js";
import * as Elevator from "./elevator.bs.js";

var AppState = Elevator.Make({
      empty: Floor.empty,
      make: Floor.make,
      moveToward: Floor.moveToward
    });

function reducer(state, action) {
  if (action) {
    return Curry._2(AppState.requestFloor, state, action._0);
  } else {
    return Curry._1(AppState.tick, state);
  }
}

var empty = AppState.empty;

export {
  AppState ,
  empty ,
  reducer ,
  
}
/* AppState Not a pure module */
