// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Elevator from "./elevator.bs.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function reducer(state, action) {
  if (action) {
    return Elevator.requestFloor(state, Caml_option.some(action._0));
  } else {
    return Elevator.tick(state);
  }
}

var empty = Elevator.empty;

export {
  empty ,
  reducer ,
  
}
/* No side effect */
