// Generated by ReScript, PLEASE EDIT WITH CARE


function next(t) {
  if (!t) {
    return /* Done */0;
  }
  var steps = t._0;
  if (steps > 1) {
    return /* Steps */{
            _0: steps - 1 | 0
          };
  } else {
    return /* Done */0;
  }
}

function toInt(t) {
  if (t) {
    return t._0;
  } else {
    return 0;
  }
}

var empty = /* Steps */{
  _0: 5
};

export {
  empty ,
  next ,
  toInt ,
  
}
/* No side effect */
