// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function StepsComp(Props) {
  var steps = Props.steps;
  return React.createElement("h1", undefined, "Steps left: " + String(steps));
}

var Int;

var make = StepsComp;

export {
  Int ,
  make ,
  
}
/* react Not a pure module */
