// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Floor from "../domain/floor.bs.js";
import * as State from "../domain/state.bs.js";
import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

import './app.css'
;

function classnames(_list, _acc) {
  while(true) {
    var acc = _acc;
    var list = _list;
    if (!list) {
      return acc;
    }
    var match = list.hd;
    if (match[1]) {
      _acc = acc + " " + match[0];
      _list = list.tl;
      continue ;
    }
    _list = list.tl;
    continue ;
  };
}

function App$FloorComp(Props) {
  var floor = Props.floor;
  var isTarget = Props.isTarget;
  var isCurrent = Props.isCurrent;
  var dispatch = Props.dispatch;
  return React.createElement("div", {
              className: classnames({
                    hd: [
                      "floor",
                      true
                    ],
                    tl: {
                      hd: [
                        "target",
                        isTarget
                      ],
                      tl: {
                        hd: [
                          "current",
                          isCurrent
                        ],
                        tl: /* [] */0
                      }
                    }
                  }, ""),
              onClick: (function (param) {
                  return Curry._1(dispatch, /* RequestFloor */{
                              _0: floor
                            });
                })
            }, Floor.toString(floor));
}

var FloorComp = {
  make: App$FloorComp
};

function App$FloorsRaw(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: "floorsRaw"
            }, Belt_Array.reverse(Belt_Array.mapWithIndex(Belt_Array.make(10, undefined), (function (index, param) {
                        return Curry._1(children, Floor.make(index));
                      }))));
}

var FloorsRaw = {
  make: App$FloorsRaw
};

function App$ElevatorComp(Props) {
  var isOpen = Props.isOpen;
  return React.createElement("div", {
              className: classnames({
                    hd: [
                      "elevator",
                      true
                    ],
                    tl: {
                      hd: [
                        "open",
                        isOpen
                      ],
                      tl: /* [] */0
                    }
                  }, "")
            });
}

var ElevatorComp = {
  make: App$ElevatorComp
};

function App(Props) {
  var match = React.useReducer(State.reducer, State.AppState.empty);
  var dispatch = match[1];
  var state = match[0];
  React.useEffect((function () {
          var timer = setInterval((function (param) {
                  return Curry._1(dispatch, /* Tick */0);
                }), 500);
          return (function (param) {
                    clearInterval(timer);
                    
                  });
        }), []);
  return React.createElement("div", {
              className: "app"
            }, React.createElement(App$FloorsRaw, {
                  children: (function (floor) {
                      return React.createElement(App$FloorComp, {
                                  floor: floor,
                                  isTarget: Curry._2(State.AppState.Selector.isTargetFloor, state, floor),
                                  isCurrent: Curry._2(State.AppState.Selector.isCurrentFloor, state, floor),
                                  dispatch: dispatch,
                                  key: Floor.toString(floor)
                                });
                    })
                }), React.createElement(App$ElevatorComp, {
                  isOpen: Curry._1(State.AppState.Selector.isOpen, state)
                }));
}

var List;

var $$Array;

var Int;

var AppState;

var Selector;

var make = App;

export {
  List ,
  $$Array ,
  Int ,
  AppState ,
  Selector ,
  classnames ,
  FloorComp ,
  FloorsRaw ,
  ElevatorComp ,
  make ,
  
}
/*  Not a pure module */
