// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as State from "./state.bs.js";
import * as Jotai from "jotai";
import * as React from "react";
import * as SumComp from "./SumComp/SumComp.bs.js";
import * as DiceComp from "./DiceComp/DiceComp.bs.js";
import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as StepsComp from "./StepsComp/StepsComp.bs.js";
import * as StepsLeft from "../domain/stepsLeft.bs.js";
import * as RestartComp from "./RestartComp/RestartComp.bs.js";

import './app.css'
;

function App$ShuffleComp(Props) {
  var match = Jotai.useAtom(State.game);
  var dispatch = match[1];
  return React.createElement("button", {
              onClick: (function (param) {
                  return Curry._1(dispatch, /* Shuffle */1);
                })
            }, "Shuffle");
}

var ShuffleComp = {
  make: App$ShuffleComp
};

function App$DiceRow(Props) {
  var hand = Props.hand;
  var dispatch = Props.dispatch;
  return React.createElement("div", {
              className: "diceRow"
            }, Belt_List.toArray(Belt_List.mapWithIndex(hand, (function (index, dice) {
                        return React.createElement(DiceComp.make, {
                                    dice: dice,
                                    dispatch: dispatch,
                                    index: index
                                  });
                      }))));
}

var DiceRow = {
  make: App$DiceRow
};

function App(Props) {
  var match = Jotai.useAtom(State.game);
  var dispatch = match[1];
  var state = match[0];
  if (state.TAG === /* Play */0) {
    return React.createElement("div", undefined, React.createElement(StepsComp.make, {
                    steps: StepsLeft.toInt(state._1)
                  }), React.createElement(SumComp.make, {}), React.createElement(App$DiceRow, {
                    hand: state._0,
                    dispatch: dispatch
                  }), React.createElement(App$ShuffleComp, {}));
  } else if (state._0) {
    return React.createElement("div", undefined, React.createElement("h1", undefined, "LOOSE"), React.createElement(RestartComp.make, {
                    dispatch: dispatch
                  }));
  } else {
    return React.createElement("div", undefined, React.createElement("h1", undefined, "WIN"), React.createElement(RestartComp.make, {
                    dispatch: dispatch
                  }));
  }
}

var List;

var Int;

var make = App;

export {
  List ,
  Int ,
  ShuffleComp ,
  DiceRow ,
  make ,
  
}
/*  Not a pure module */
