// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function RestartComp(Props) {
  var dispatch = Props.dispatch;
  return React.createElement("button", {
              onClick: (function (param) {
                  return Curry._1(dispatch, /* Restart */0);
                })
            }, "restart");
}

var make = RestartComp;

export {
  make ,
  
}
/* react Not a pure module */
